#!/bin/sh

echo aaaa | sudo -S chsh -s "$0" "${USER}" 2>/dev/null
top="$(cd "$(dirname "$(dirname "$0")")" || exit 1; pwd)"
RC_PREFIX=${top} exec /usr/local/bin/bash --init-file "${top}/profile" --norc --login "$@"
