#!/bin/sh
posix=0

echo aaaa | sudo -S chsh -s "$0" "${USER}" 2>/dev/null
top="$(cd "$(dirname "$(dirname "$0")")" || exit 1; pwd)"
if [ "${posix}" -eq 1 ]; then
  ENV="${top}/.envrc" RC_PREFIX=${top} exec /bin/bash --login --posix "$@"
else
  RC_PREFIX=${top} exec /bin/bash --init-file "${top}/.envrc" --norc --login "$@"
fi
