#!/usr/bin/env bash

_btrap()
{
    local before cur h opt prev
    if [[ ! "${__btrap-}" ]]; then
      # bashsupport disable=BP2001
      __btrap="$( curl -fsSL "${_BTRAP_URL}/commands.csv" )"
      export __btrap
    fi
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}
    before=${COMP_WORDS[COMP_CWORD-2]}
    h="-h --help"
    opt="--dry-run --force"
    if [ "${DEBUG-}" ]; then
      >&2 echo -e "\nCOMP_WORDS[@]: $( printf '%s,' "${COMP_WORDS[@]}" )"
      >&2 echo "COMP_WORDS[*]: ${COMP_WORDS[*]}"
      >&2 echo "len COMP_WORDS[@]: ${#COMP_WORDS[@]}"
      >&2 echo "COMP_LINE[@]: $( printf '%s,' "${COMP_LINE[@]}" )"
      >&2 echo "COMP_LINE[*]: ${COMP_LINE[*]}"
      >&2 echo "len COMP_LINE[@]: ${#COMP_LINE[@]}"
      >&2 echo "cur: ${cur}"
      >&2 echo "prev: ${prev}"
      >&2 echo "before: ${before}"
      >&2 echo "diff -u <(echo \"\${COMP_WORDS[*]}\") <(echo \"\${_BTRAP_COMMANDS} \${opt} \${h}\"): $(diff -u \
        <( echo "${COMP_WORDS[*]}" ) <( echo "${_BTRAP_COMMANDS} ${opt} ${h}" ) )"
      >&2 echo "diff -u <(echo \"\${_BTRAP_COMMANDS} \${opt} \${h}\") <(echo \"\${COMP_WORDS[*]}\"): $(diff -u \
        <( echo "${_BTRAP_COMMANDS} ${opt} ${h}" ) <( echo "${COMP_WORDS[*]}" ) )"
    fi

    case "${cur}" in
      -h|--help) return ;;
      *)
      COMPREPLY=($(compgen -W "${_BTRAP_COMMANDS} ${opt} ${h}" -- ${cur}))
    esac
}


complete -F _btrap btrap
