#!/bin/bash
set -e

main() {
  local image tag
  while read -r image tag; do
    echo "${image} ${tag}"
    docker build --build-arg image="${image}" --target build --tag "${tag}" .
  done <<< "${images}"
}

main

