#!/bin/sh
set -e
set -x

if ! command -v rc >/dev/null; then
  output="/tmp/rc.d"
  tar="/tmp/main"
  url="https://github.com/j5pu/rc.d/tarball/main"

  rm -rf "${output}" "${tar}"
  mkdir -p "${output}"

  if command -v wget > /dev/null; then
    wget --quiet -O "${tar}" "${url}"
  elif command -v curl > /dev/null; then
    curl -sL -o "${tar}" "${url}"
  elif command -v git >/dev/null; then
    git clone "https://github.com/j5pu/rc.d" "${output}"
  else
    echo "git, curl or wget: not found"
    exit 1
  fi
  [ -f "${tar}" ] && [ ! -d "${output}" ] && mkdir "${output}" && tar -xf "${tar}" -C "${output}" --strip-components=1
  rc="${output}/bin/rc"
  { [ -f "${rc}" ] && chmod +x "${rc}" && [ -x "${output}/bin/rc" ]; } || { echo "${rc}: command not found"; exit 1; }
fi

exec ${rc:-rc} --install "${@}"
