#!/bin/sh
set -e
trap 'rc=$?; [ $rc -ne 0 ] && echo "${err:-error not traced}"; exit $rc' EXIT

[ "${SELFINSTALL-}" ] && unset SELFINSTALL && git all && curl -fsSL "https://git.io/rc.d" | sh && exit

echo $0

export err

if ! command -v rc >/dev/null; then
  output="/tmp/rc.d"
  tar="/tmp/main"
  url="https://github.com/j5pu/rc.d/tarball/main"

  rm -rf "${output}" "${tar}"

  err="download error"
  if command -v wget > /dev/null; then
    wget --quiet -O "${tar}" "${url}"
  elif command -v curl > /dev/null; then
    curl -sL -o "${tar}" "${url}"
  elif command -v git >/dev/null; then
    git clone "https://github.com/j5pu/rc.d" "${output}"
  else
    err="git, curl or wget: not found"
    false
  fi

  [ -f "${tar}" ] && [ ! -d "${output}" ] && mkdir "${output}" && tar -xf "${tar}" -C "${output}" --strip-components=1
  rc="${output}/bin/rc"
  err="${rc}: command not found"
  [ -f "${rc}" ] && chmod +x "${rc}" && [ -x "${rc}" ]
fi
exec ${rc:-rc} --install "${@}"
