#!/bin/sh
#
# rc.d install script: --self to push repo and use the latest version of install script and repository.

set -e
trap 'rc=$?; [ $rc -ne 0 ] && echo "${err:-error not traced}"; exit $rc' EXIT

{

[ "${1}" = "--self" ] && git all && curl -fsSL "https://git.io/rc.d" | sh && exit

export err

if ! command -v rc >/dev/null; then
  output="/tmp/rc.d"
  tar="/tmp/main"
  url="https://github.com/j5pu/rc.d/tarball/main"

  rm -rf "${output}" "${tar}"

  err="download error"
  if command -v wget > /dev/null; then
    wget --quiet -O "${tar}" "${url}"
  elif command -v curl > /dev/null; then
    curl -sL -o "${tar}" "${url}"
  elif command -v git >/dev/null; then
    git clone --quiet "https://github.com/j5pu/rc.d" "${output}"
  else
    err="git, curl or wget: not found"
    false
  fi

  [ -f "${tar}" ] && [ ! -d "${output}" ] && mkdir "${output}" && tar -xf "${tar}" -C "${output}" --strip-components=1
  cmd="${output}/bin/rc"
  err="${cmd}: command not found"
  [ -f "${cmd}" ] && chmod +x "${cmd}" && [ -x "${cmd}" ]
fi
exec ${cmd:-rc} --install "${@}"

}
