#!/bin/sh
# TODO: install https://github.com/jakewendt/envv
# TODO: mirar bien el que hace parsing https://github.com/kellyjonbrazil/jc#parsers
# TODO: doppler (curl -Ls --tlsv1.2 --proto "=https" --retry 3 https://cli.doppler.com/install.sh || wget -t 3 -qO- https://cli.doppler.com/install.sh) | sh
# TODO: Puedo tener mi propio install sin que sea paquete, que al final solo hay que copiar los ficheros y que dependa de si hay python o no !!
#  https://gget.io/
# TODO: Ver los paths que se instalaria los man pages y los ifo en cada systema y actualizar una variabe

