#!/bin/sh
# shellcheck disable=SC1090

###################################### RC
RC_BASH=true
RC_CURL=false
RC_DOCKER=true
RC_GIT=true
RC_GIT_PROMPT=false
RC_ITERM_SHELL_INTEGRATION=true
RC_LS=true
RC_PS1=false
RC_ROOT=true
RC_STARSHIP=true

###################################### SHOPT
# https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html
if [ "${BASH_VERSINFO-}" ]; then
  if ! shopt -oq posix && [ "${BASH_VERSINFO[0]}" -gt 3 ]; then
    shopt -qs direxpand globstar
  fi
fi

if [ ! "${PS1-}" ]; then
  return
fi

shopt -qs checkwinsize histappend

###################################### PATH
# export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
PATH="\
${PYCHARM}:\
${PYCHARM_CONTENTS}/MacOS:\

###################################### COMPLETIONS
# BASH_COMPLETION_COMPAT_DIR
# BASH_COMPLETION_USER_FILE
for i in "${BREW_PREFIX}"/etc/profile.d/*.sh; do
  . "${i}"
done

if [ "${BASH_VERSINFO[0]}" -gt 4 ]; then
  shopt -qs no_empty_cmd_completion progcomp_alias
fi

complete -c -F _minimal source


if [ "${BASH_VERSINFO-}" ]; then
  ###################################### ITERM SHELL INTEGRATION
  # https://iterm2.com/documentation-shell-integration.html
  # LOAD_COMPOSED_FUNCTIONS     "0" disables automatically sourcing of all of composed functions
  #                             when composure.sh is sourced
  if $RC_ITERM_SHELL_INTEGRATION; then
    file="${XDG_DATA_HOME}/iterm2_shell_integration.bash"
    if [ ! -f "${file}" ]; then
      curl -qSsL "https://iterm2.com/shell_integration/bash" > "${file}"
    fi
    . "${file}"
    unset file
  fi
###################################### LS_COLORS
# https://github.com/trapd00r/LS_COLORS
if $RC_LS; then
  if which gdircolors > /dev/null && which gls > /dev/null; then
    cmd="gdircolors"
    LS="gls"
  else
    cmd="dircolors"
    LS="ls"
  fi

  if command -v "${cmd}" > /dev/null; then
    export COLUMNS  # Remember columns for subprocesses.
    eval "$(${cmd})"
    ls() {
      command ${LS} -F -h --color=always -v --author --time-style=long-iso -C "${@}" | less -R -X -F
    }
    alias ll="ls -l"
    alias l="ls -l -a"

    unset directory file
  fi
  unset cmd
else
  unset LS_COLORS
  unset -f ls
  alias ls="ls -h"
  alias ll="ls -l"
  alias l="ls -l -a"
fi


###################################### COMPOSURE
# https://github.com/erichs/composure
# LOAD_COMPOSED_FUNCTIONS     "0" disables automatically sourcing of all of composed functions
#                             when composure.sh is sourced
if $RC_COMPOSURE; then
  export LOAD_COMPOSED_FUNCTIONS
  repo="composure"
  dest="${CACHE}/${repo}"
  file="${CACHE}/${repo}/${repo}.sh"
  mkdir -p "${CACHE}"
  if test -d "${dest}"; then
    git -C "${dest}" pull --quiet --force 1>/dev/null
  else
    git clone --quiet "https://github.com/erichs/${repo}.git" "${dest}" 1>/dev/null
  fi
  [ -r "${file}" ] && . "${file}"
  unset dest file name
fi
