#!/bin/sh

# --password
# --usr (esto lo lia porque lo que hace es escribir el fichero con ese usuari pero si es de root no deja)
# --sudoers
# -H
# --system no usa el sudo con el commando tambien podria hacerlo con el python en lugar del sudo .


if ! cmd="$(which -a "$(basename "${0}")" | sed -n "2 p")"; then
  exit 1
fi
printf "%\n" "${password}" | sudo -S true

bypass=false

for arg do
  skip=true
  case "${1}" in
    -h|--help) $( which man ) -p cat "$(basename "${0}")" 2>/dev/null; exit ;;
    --bypass) bypass=true ;;
    *) skip=false ;;
  esac
  shift
  $skip || set -- "$@" "${arg}"  # save original
done

echo "${@}"

${cmd} "${@}"


#--system macOS no
#--user|-u
#-H
#que haga login el ssh por defecto
#que el sudo sea por defecto login asi solo pongo uno?
#y el rsync
#o hacerlo con funciones
