'\" t
.\"     Title: asciiman
.\"    Author: author
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-11-29
.\"    Manual: Asciiman Manual - rc.d
.\"    Source: Asciiman 0.0.1
.\"  Language: English
.\"
.TH "ASCIIMAN" "1" "2021-11-29" "Asciiman 0.0.1" "Asciiman Manual \- rc.d"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
asciiman \- converts, tests and commit changes for AsciiDoc man pages in a repository
.SH "SYNOPSIS"
.sp
\fBasciiman\fP [\fIOPTION\fP] [\fIDIRECTORY\fP]
.SH "DESCRIPTION"
.sp
The \fBasciiman\fP command will find man pages in a valid repository \fIDIRECTORY\fP,
will replace existing man page if generated man page has changed, will test and commit changes.
.br
.sp
Man pages will be installed in \f(CR../../share/man/man1\fP with respect to the directory
where the source \f(CR*.adoc\fP has been found, i.e.: \f(CR./src/man/name.adoc\fP will be generated to \f(CR./share/man/man1/name.1\fP.
.SH "OPTIONS"
.sp
\fB\-\-help\fP
.RS 4
Show man page and exit.
.RE
.sp
\fBDIRECTORY\fP
.RS 4
Directory in a git repository (default: current working directory).
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Invalid git repository.
.br
Error converting from AsciiDoc to man page.
.br
Testing error.
.RE
.SH "EXAMPLES"
.sp
$ asciiman
.sp
$ asciiman src/man
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "AUTHOR"
.sp
j5pu