'\" t
.\"     Title: colon
.\"    Author: author
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-11-29
.\"    Manual: Colon Manual - rc.d
.\"    Source: Colon 0.0.1
.\"  Language: English
.\"
.TH "COLON" "1" "2021-11-29" "Colon 0.0.1" "Colon Manual \- rc.d"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
colon \- prepend (beginning), append (end) or remove to colon variables (PATH, INFOPATH, MANPATH etc.)
.SH "SYNOPSIS"
.sp
\fBcolon\fP \fIDIRECTORY\fP [\fIPATH\fP] [\fIOPTION\fP]
.SH "DESCRIPTION"
.sp
The \fBcolon\fP command will:
\- \fBprepend\fP (beginning),
.br
\- \fBappend\fP (end) or
.br
\- \fBremove\fP
.br
a \fIDIRECTORY\fP to a \fIPATH\fP colon type variable.
.SH "OPTIONS"
.SS "Optional Arguments"
.sp
\fB\-\-help\fP
.RS 4
Show man page and exit.
.RE
.sp
\fB\-B, \-\-base\-dir\fP=\fIDIR\fP, \fBDIRECTORY\fP
.RS 4
Directory in a git repository (default: current working directory).
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Invalid git repository.
.br
Error converting from AsciiDoc to man page.
.br
Testing error.
.RE
.SH "EXAMPLES"
.sp
\fI$\fP \fBcolon\fP
.sp
\fI$\fP \fBcolon\fP src/man
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "AUTHOR"
.sp
j5pu