'\" t
.\"     Title: colon
.\"    Author: author
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-11-29
.\"    Manual: Colon Manual - rc.d
.\"    Source: Colon 0.0.1
.\"  Language: English
.\"
.TH "COLON" "1" "2021-11-29" "Colon 0.0.1" "Colon Manual \- rc.d"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
colon \- prepend (beginning, the default), append (end) or remove to colon variables (PATH, INFOPATH, MANPATH etc.)
.SH "SYNOPSIS"
.sp
\fBcolon\fP \fIDIRECTORY\fP [\fIPATH\fP] [\fIOPTION\fP]
.SH "DESCRIPTION"
.sp
The \fBcolon\fP command will:
.br
\- \fBprepend\fP (beginning, the \fIdefault\fP),
.br
\- \fBappend\fP (end)
.br
\- or \fBremove\fP
.br
a \fIDIRECTORY\fP to a \fIPATH\fP colon type variable.
.SH "OPTIONS"
.SS "Arguments"
.sp
\fBDIRECTORY\fP
.RS 4
Absolute \fIdirectory\fP (start with \f(CR/\fP) or \f(CR.\fP, to be prepended, appended or removed.
.RE
.SS "Optional Arguments"
.sp
\fBPATH\fP
.RS 4
\fIPath\fP colon type variable to manipulate, i.e.: \f(CR/foo:/bar\fP (default: \*(Aq\*(Aq).
.RE
.sp
\fB\-\-append\fP
.RS 4
Add at the end.
.RE
.sp
\fB\-\-remove\fP
.RS 4
Remove for the path value.
.RE
.sp
\fB\-\-desc\fP
.RS 4
Show one line description and exit.
.RE
.sp
\fB\-h, \-\-help\fP
.RS 4
Show man page and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
\fIDirectory\fP must be absolute / or .
.br
.RE
.SH "EXAMPLES"
.sp
\fI$\fP \fBcolon\fP \fI/foo\fP
.br
foo
.br
.sp
\fI$\fP \fBcolon\fP \fI/foo\fP /bar
.br
/foo:/bar
.br
.sp
\fI$\fP \fBcolon\fP \fI/foo\fP /bar \-\-append
.br
/bar:/foo
.br
.sp
\fI$\fP \fBcolon\fP \-\-append /foo /bar
.br
/bar:/foo
.br
.sp
\fI$\fP \fBcolon\fP \fI/foo\fP /bar:/foo
.br
/bar
.br
.sp
\fI$\fP \fBcolon\fP \fI/foo\fP \-\-remove /bar:/foo
.br
/bar
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "AUTHOR"
.sp
j5pu