'\" t
.\"     Title: rc_d_test
.\"    Author: j5pu
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2021-12-08
.\"    Manual: Rc_d_test Manual
.\"    Source: Rc_d_test 0.0.1
.\"  Language: English
.\"
.TH "*RC_D_TEST*" "1" "2021-12-08" "Rc_d_test 0.0.1" "Rc_d_test Manual"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
*rc_d_test* \- DEBUG:
DRYRUN:
QUIET:
VERBOSE:
WARNING:
args: \-\-desc
\-\-desc
.SH "SYNOPSIS"
.sp
\fBrc_d_test\fP [\fIINFO ARGUMENT\fP] [\fICOMMON OPTION\fP] [\fIOPTIONAL ARGUMENT\fP] \fIARGUMENT\fP...
.SH "DESCRIPTION"
.sp
The \fBrc_d_test\fP command
.SH "OPTIONS"
.SS "ARGUMENTS"
.sp
\fBARGUMENT\fP
.RS 4
Required \fIARGUMENT\fP.
.RE
.SS "OPTIONAL ARGUMENTS"
.sp
\fB\-\-optional\fP
.RS 4
\fIOPTIONAL\fP argument.
.RE
.SS "COMMON OPTIONS"
.sp
\fB\-\-debug\fP
.RS 4
Show debug output.
.RE
.sp
\fB\-\-quiet\fP
.RS 4
Silent output.
.RE
.sp
\fB\-\-warning\fP
.RS 4
Show warnings.
.RE
.sp
\fB\-\-verbose\fP
.RS 4
Verbose output.
.RE
.SS "INFO ARGUMENTS"
.sp
\fB\-h, \-\-help\fP
.RS 4
Show man page and exit.
.RE
.sp
\fB\-\-desc\fP
.RS 4
Show one line description and exit.
.RE
.sp
\fB\-\-version\fP
.RS 4
Show version and exit.
.RE
.SH "EXIT STATUS"
.sp
\fB0\fP
.RS 4
Success.
.RE
.sp
\fB1\fP
.RS 4
Error.
.br
.RE
.SS "ENVIRONMENT"
.sp
\fBDEBUG\fP
.RS 4
Set \fBDEBUG\fP=\fI1\fP for debug output (\fIdefault\fP: \fIunset\fP).
.RE
.sp
\fBQUIET\fP
.RS 4
Set \fBQUIET\fP=\fI1\fP to silent output (\fIdefault\fP: \fIerror\fP and \fIok\fP messages are shown).
\fBQUIET\fP takes precedence over \fIDEBUG\fP, \fIVERBOSE\fP and \fIWARNING\fP.
.RE
.sp
\fBVERBOSE\fP
.RS 4
Set \fBVERBOSE\fP=\fI1\fP to show verbose messages (\fIdefault\fP: \fIunset\fP).
.RE
.sp
\fBWARNING\fP
.RS 4
Set \fBWARNING\fP=\fI1\fP to show warning messages (\fIdefault\fP: \fIunset\fP).
.RE
.SS "OUTPUT"
.sp
See \fICOMMON OPTIONS\fP and \fIENVIRONMENT\fP sections.
.SH "EXAMPLES"
.sp
\fI$\fP \fBrc_d_test\fP
.sp
\fI$\fP \fBrc_d_test\fP
output
.SH "REPOSITORY"
.sp
rc.d
.SH "RESOURCES"
.sp
\fBGitHub:\fP \c
.URL "https://github.com/j5pu/rc.d" "" ""
.SH "COPYING"
.sp
Copyright \(co 2021\-present j5pu.
.br
Free use of this software is granted under the terms of the MIT License.
.SH "SEE ALSO"
.sp
manpage(1)
.SH "AUTHOR"
.sp
j5pu