#!/bin/sh

main () {
  name="$(basename "${0}")"
  cmd="$(has -v "${name}")" || die "${name}": "${name}": command not found
  echo "exec ${cmd} --init-file /etc/profile --rcfile /etc/profile --login ${*}" 2>/tmp/"${name}"
  exec ${cmd} --init-file /etc/profile --rcfile /etc/profile --login "${@}";
}

main "${@}"


