#!/bin/sh

# List all files in git dir but ignored, from 'git ls-files'
# Silents errors by default, use --noquiet or QUIET=1 to see errors.
#
: git ls-files

. helpers.lib

if test "$#" -eq 0 || { test "${1-}" = '--parsed' && shift; }; then
  unset PARSED
  for arg do
    shift
    case "${arg}" in
      -C) continue; shift; path="${arg}" ;;
      *) path="${arg}"
    esac
  done
  /usr/local/bin/git ls-files --cached --deduplicate --deleted --error-unmatch --full-name \
    --modified --others "${path:-.}"
else
  PARSE="${0}" parse "$@"
fi
