#!/bin/sh

# Repository remote repository owner and name, from url or repository git config
# Silents errors by default, use --noquiet or QUIET=1 to see errors.
#
# https://github.com/owner/name.git
# git@github.com:owner/name.git
# git+ssh://git@github.com/owner/name.git
: git config

. helpers.lib

if [ ! "${1-}" ] || [ "${PARSED-}" ]; then
  unset PARSED
  error=false

  if ! echo "${1:-}" | \
    grep -qvE ':|github.com|gitlab.com|bitbucket.org|https|git@|git+|googlesource.com|pagure.io'; then
    real="${1:-}"
  else
    if ! real="$(QUIET="${QUIET:-1}" git-url "$@")"; then
      QUIET="${QUIET:-1}" die "${real}"
    fi
  fi

  if test "${real-}"; then
    rv="$(echo "${real}" | awk -F '[/:]' '{ if (NF >= 2) sub(/.git$/, ""); print $(NF-1), $(NF); }')"
    test "${rv}" || error=true
  else
    error=true
    QUIET="${QUIET:-1}" die Invalid Input: \$1="${1:-}"
  fi

  ! $error || QUIET="${QUIET:-1}" die  --white \$*="$*", rv: "${rv}"

  echo "${rv}"
else
  PARSE="${0}" parse "$@"
fi
