#!/bin/bash
set -e

images="alpine
archlinux
bash
bash 5.1
bash 5.0
bash 4.4
bats/bats
busybox
centos
debian
debian bullseye-backports
debian bullseye-slim
fedora
jrei/systemd-ubuntu
kalilinux/kali-rolling
kalilinux/kali-bleeding-edge
nixos/nix
python 3.9-alpine
python 3.9-bullseye
python 3.9-slim
python 3.10-alpine
python 3.10-bullseye
python 3.10-slim
richxsl/rhel7
ubuntu
zshusers/zsh"

declare -A targets=( ["bash"]="bash debian kalilinux ubuntu" ["bin_bash"]="centos fedora richxsl" ["sh"]="alpine busybox nix" ["usr_bin_bash"]="archlinux")

#######################################
# Docker hub build hook
# https://docs.docker.com/docker-hub/builds/advanced/
# https://dev.to/samuelea/automate-your-builds-on-docker-hub-by-writing-a-build-hook-script-13fp
# https://codeclimbing.com/automate-your-builds-on-docker-hub-by-writing-a-build-hook-script/
# on macOS builds for linux/amd64 (OS, ARCH). Igual hay ue compilar para ms pero el mac no puede
# COMMIT_MSG:         Message from the commit being tested and built.
# DOCKER_REPO:        Name of the Docker repository being built (index.docker.io/<USER>/<repo>)
# DOCKER_TAG:         Docker repository tag being built.
# DOCKERFILE_PATH:    Dockerfile currently being built.
# IMAGE_NAME:         Name and tag of the Docker repository being built.
#                     (This variable is a combination of DOCKER_REPO:DOCKER_TAG.)
# SOURCE_BRANCH:      Name of the branch or the tag that is currently being tested.
# SOURCE_COMMIT:      SHA1 hash of the commit being tested.
#######################################
build() {
  docker build --build-arg base --build-arg tag --tag "${image}" .
}

info() {
  local base_repo base_tag
  while read -r base_repo base_tag; do
    :
  done <<< "${images}"
}
#######################################
# Main function
# Globals:
#   DOCKERFILE_PATH:  Dockerfile currently being built.
#   HUB:              Running in auto build Docker Hub.
#######################################
main() {
  export DOCKERFILE_PATH HUB=true
  if [ ! "${DOCKERFILE_PATH-}" ]; then
    HUB=false
    DOCKERFILE_PATH="$(dirname "${0}")/../Dockerfile"
    case "${1}" in build|info) ${1} ;; esac
  else
    HUB=true
    build "${@}"
  fi



}


main "${@}"
