#!/bin/sh

main () {
  name="$(basename "${0}")"
  cmd="$(has -v "${name}")" || die "${name}": "${name}": command not found
  echo "exec ${cmd} ${*}" 2>/tmp/"${name}"
  exec ${cmd} "${@}";
}

main "${@}"


