#!/bin/sh
# shellcheck disable=SC2034
set -eu

f() {
  if v="$(git mierda)"; then
    echo true
  else
    echo error
    false
  fi
}

tmp="$(mktemp -d)"
for i in "${tmp}"/*.sh ; do
  . "${i}"
done 2>/dev/null || true
