# shellcheck shell=sh disable=SC2034

# (auto generated by: tools/color.sh)

# <html><h2>Reset </h2>
# <p><strong><code>$Reset</code></strong> Color Reset .</p>
# </html>
export Reset

# <html><h2>Black </h2>
# <p><strong><code>$Black</code></strong> Color Black .</p>
# </html>
export Black

# <html><h2>Black Bold</h2>
# <p><strong><code>$BlackBold</code></strong> Color Black Bold.</p>
# </html>
export BlackBold

# <html><h2>Black Dim</h2>
# <p><strong><code>$BlackDim</code></strong> Color Black Dim.</p>
# </html>
export BlackDim

# <html><h2>Black Under</h2>
# <p><strong><code>$BlackUnder</code></strong> Color Black Under.</p>
# </html>
export BlackUnder

# <html><h2>Black Invert</h2>
# <p><strong><code>$BlackInvert</code></strong> Color Black Invert.</p>
# </html>
export BlackInvert

# <html><h2>Black Bg</h2>
# <p><strong><code>$BlackBg</code></strong> Color Black Bg.</p>
# </html>
export BlackBg

# <html><h2>Red </h2>
# <p><strong><code>$Red</code></strong> Color Red .</p>
# </html>
export Red

# <html><h2>Red Bold</h2>
# <p><strong><code>$RedBold</code></strong> Color Red Bold.</p>
# </html>
export RedBold

# <html><h2>Red Dim</h2>
# <p><strong><code>$RedDim</code></strong> Color Red Dim.</p>
# </html>
export RedDim

# <html><h2>Red Under</h2>
# <p><strong><code>$RedUnder</code></strong> Color Red Under.</p>
# </html>
export RedUnder

# <html><h2>Red Invert</h2>
# <p><strong><code>$RedInvert</code></strong> Color Red Invert.</p>
# </html>
export RedInvert

# <html><h2>Red Bg</h2>
# <p><strong><code>$RedBg</code></strong> Color Red Bg.</p>
# </html>
export RedBg

# <html><h2>Green </h2>
# <p><strong><code>$Green</code></strong> Color Green .</p>
# </html>
export Green

# <html><h2>Green Bold</h2>
# <p><strong><code>$GreenBold</code></strong> Color Green Bold.</p>
# </html>
export GreenBold

# <html><h2>Green Dim</h2>
# <p><strong><code>$GreenDim</code></strong> Color Green Dim.</p>
# </html>
export GreenDim

# <html><h2>Green Under</h2>
# <p><strong><code>$GreenUnder</code></strong> Color Green Under.</p>
# </html>
export GreenUnder

# <html><h2>Green Invert</h2>
# <p><strong><code>$GreenInvert</code></strong> Color Green Invert.</p>
# </html>
export GreenInvert

# <html><h2>Green Bg</h2>
# <p><strong><code>$GreenBg</code></strong> Color Green Bg.</p>
# </html>
export GreenBg

# <html><h2>Yellow </h2>
# <p><strong><code>$Yellow</code></strong> Color Yellow .</p>
# </html>
export Yellow

# <html><h2>Yellow Bold</h2>
# <p><strong><code>$YellowBold</code></strong> Color Yellow Bold.</p>
# </html>
export YellowBold

# <html><h2>Yellow Dim</h2>
# <p><strong><code>$YellowDim</code></strong> Color Yellow Dim.</p>
# </html>
export YellowDim

# <html><h2>Yellow Under</h2>
# <p><strong><code>$YellowUnder</code></strong> Color Yellow Under.</p>
# </html>
export YellowUnder

# <html><h2>Yellow Invert</h2>
# <p><strong><code>$YellowInvert</code></strong> Color Yellow Invert.</p>
# </html>
export YellowInvert

# <html><h2>Yellow Bg</h2>
# <p><strong><code>$YellowBg</code></strong> Color Yellow Bg.</p>
# </html>
export YellowBg

# <html><h2>Blue </h2>
# <p><strong><code>$Blue</code></strong> Color Blue .</p>
# </html>
export Blue

# <html><h2>Blue Bold</h2>
# <p><strong><code>$BlueBold</code></strong> Color Blue Bold.</p>
# </html>
export BlueBold

# <html><h2>Blue Dim</h2>
# <p><strong><code>$BlueDim</code></strong> Color Blue Dim.</p>
# </html>
export BlueDim

# <html><h2>Blue Under</h2>
# <p><strong><code>$BlueUnder</code></strong> Color Blue Under.</p>
# </html>
export BlueUnder

# <html><h2>Blue Invert</h2>
# <p><strong><code>$BlueInvert</code></strong> Color Blue Invert.</p>
# </html>
export BlueInvert

# <html><h2>Blue Bg</h2>
# <p><strong><code>$BlueBg</code></strong> Color Blue Bg.</p>
# </html>
export BlueBg

# <html><h2>Magenta </h2>
# <p><strong><code>$Magenta</code></strong> Color Magenta .</p>
# </html>
export Magenta

# <html><h2>Magenta Bold</h2>
# <p><strong><code>$MagentaBold</code></strong> Color Magenta Bold.</p>
# </html>
export MagentaBold

# <html><h2>Magenta Dim</h2>
# <p><strong><code>$MagentaDim</code></strong> Color Magenta Dim.</p>
# </html>
export MagentaDim

# <html><h2>Magenta Under</h2>
# <p><strong><code>$MagentaUnder</code></strong> Color Magenta Under.</p>
# </html>
export MagentaUnder

# <html><h2>Magenta Invert</h2>
# <p><strong><code>$MagentaInvert</code></strong> Color Magenta Invert.</p>
# </html>
export MagentaInvert

# <html><h2>Magenta Bg</h2>
# <p><strong><code>$MagentaBg</code></strong> Color Magenta Bg.</p>
# </html>
export MagentaBg

# <html><h2>Cyan </h2>
# <p><strong><code>$Cyan</code></strong> Color Cyan .</p>
# </html>
export Cyan

# <html><h2>Cyan Bold</h2>
# <p><strong><code>$CyanBold</code></strong> Color Cyan Bold.</p>
# </html>
export CyanBold

# <html><h2>Cyan Dim</h2>
# <p><strong><code>$CyanDim</code></strong> Color Cyan Dim.</p>
# </html>
export CyanDim

# <html><h2>Cyan Under</h2>
# <p><strong><code>$CyanUnder</code></strong> Color Cyan Under.</p>
# </html>
export CyanUnder

# <html><h2>Cyan Invert</h2>
# <p><strong><code>$CyanInvert</code></strong> Color Cyan Invert.</p>
# </html>
export CyanInvert

# <html><h2>Cyan Bg</h2>
# <p><strong><code>$CyanBg</code></strong> Color Cyan Bg.</p>
# </html>
export CyanBg

# <html><h2>Grey </h2>
# <p><strong><code>$Grey</code></strong> Color Grey .</p>
# </html>
export Grey

# <html><h2>Grey Bold</h2>
# <p><strong><code>$GreyBold</code></strong> Color Grey Bold.</p>
# </html>
export GreyBold

# <html><h2>Grey Dim</h2>
# <p><strong><code>$GreyDim</code></strong> Color Grey Dim.</p>
# </html>
export GreyDim

# <html><h2>Grey Under</h2>
# <p><strong><code>$GreyUnder</code></strong> Color Grey Under.</p>
# </html>
export GreyUnder

# <html><h2>Grey Invert</h2>
# <p><strong><code>$GreyInvert</code></strong> Color Grey Invert.</p>
# </html>
export GreyInvert

# <html><h2>Grey Bg</h2>
# <p><strong><code>$GreyBg</code></strong> Color Grey Bg.</p>
# </html>
export GreyBg

